### ISSUE TITLE
Redondeo en las líneas de facturas de compra (Precio)

### ISSUE THREAD

**Issue by gervacio24** [eneldoserrata/quirofanos#10]
Permitir que los precios acepten después del punto 6 cifras.

**Comment by gervacio24** [comment]
Actualmente cuando registran una compra, en la línea de factura, el precio que digitan se redondea automático, pero ellos siempre utilizan todas las cifras después del cero (Ej: 22.174859), entonces como el precio sólo acepta dos cifras después del punto, le hace un redondeo y esto le está causando inconsistencia porque la factura le está saliendo con un monto mayor

**Comment by eneldoserrata** [comment]
@gervacio24 se fijo la precision decimal para el precio de venta a 6
