### ISSUE TITLE
Duplicidad de Lotes

### ISSUE THREAD

**Issue by gervacio24** [eneldoserrata/quirofanos#11]
Permitir que se pueda duplicar el No. de lote o serie a diferentes productos.

**Comment by gervacio24** [comment]
Actualmente cuando se va a crear una orden de compras se genera el siguiente error debido a que no permite tener un mismo No. de Lote o serie para diferentes productos:

![thumbnail_image001](https://user-images.githubusercontent.com/37870827/38342769-574c7cd8-384e-11e8-841e-1bf011e29096.jpg)

**Comment by eneldoserrata** [comment]
@raponte25 @aleruizav Se debe realizar la revicion de la configuracion de lotes a nivel de producto y de tipo de conduce

**Comment by raponte25** [comment]
Esta tarea ya fue terminada. El error estaba al momento de elegir el lote, en la orden de compra. Eligiendo un lote diferente al ya creado.
