### ISSUE TITLE
Error de redondeo en unidad de medida

### ISSUE THREAD

**Issue by gervacio24** [eneldoserrata/quirofanos#12]
No permite validar órdenes de compra debido al siguiente error:

**Comment by gervacio24** [comment]
![thumbnail_image001 1](https://user-images.githubusercontent.com/37870827/38343015-98b5ccd2-384f-11e8-9605-ed14d401e26c.jpg)

**Comment by raponte25** [comment]
Este problema ya fue resuelto. El error estaba a nivel de productos.
