### ISSUE TITLE
Error al crear No. de Lote

### ISSUE THREAD

**Issue by gervacio24** [eneldoserrata/quirofanos#13]
Cuando se va a registrar en el  módulo de inventario el No. de Lote de un producto, para darle salida a la orden de entrega generada por una cotización, genera el siguiente error:

**Comment by gervacio24** [comment]
![screenshot-2018-4-5 control de despacho 00000063 - odoo](https://user-images.githubusercontent.com/37870827/38343313-3141cf2c-3851-11e8-97f1-55492675359e.png)

**Comment by eneldoserrata** [comment]
Repetida #11

**Comment by raponte25** [comment]
Listo.
