### ISSUE TITLE
Creación de Kit de Productos

### ISSUE THREAD

**Issue by gervacio24** [eneldoserrata/quirofanos#17]
Requieren que algunos productos estén enlazados con un kit que cuando se saque ese kit salgan también los productos que estén dentro de ese kit, sin tener que escogerlos por separado uno por uno.

**Comment by raponte25** [comment]
Ya esta resuelto esta parte. Se le dio el entranamiento correspondiente a la Encargada de Compras. Jamelys Lopez.
